branch-defaults:
  master:
    environment: test-ck
environment-defaults:
  test-ck:
    branch: null
    repository: null
global:
  application_name: test-ck
  default_ec2_keyname: docker-test
  default_platform: Multi-container Docker running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: lumen
  sc: git
  workspace_type: Application
