version: 2
jobs:
  deploy:
        docker:
            - image: circleci/python:2.7
        steps:
            - checkout
            - run:
               name: Install awscli
               command: |
                  sudo pip install awsebcli --upgrade

            - run:
                name: Create AWS credentials manually
                command: |
                  mkdir ~/.aws
                  touch ~/.aws/config
                  chmod 600 ~/.aws/config
                  echo "[profile eb-cli]" > ~/.aws/config
                  echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
                  echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config

            - run: 
                name: Create a Zip file 
                command: |
                  zip -r app.zip *
                  echo $CIRCLE_BRANCH
            - run: 
                name: Deploy Master branch
                command: |
                   if [[ $(echo "$CIRCLE_BRANCH" | grep -c "master/*") -eq 1 ]]; then
                   sh run-master.sh ; elif [[ $(echo "$CIRCLE_BRANCH" | grep -c "release/*") -eq 1 ]]; then
                   sh run-release.sh ; else echo $CIRCLE_BRANCH; fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master
                - develop
                - docker